"""
Gas Pipeline Data Staleness Checker
Reads corridor_pipeline_tracker.json, checks each pipeline's last_refreshed
against its refresh_frequency_days, and creates GitHub Issues for overdue data.

Run weekly via GitHub Actions or manually via workflow_dispatch.
"""

import json
import os
import sys
import requests
from datetime import datetime, timedelta

TRACKER_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'data', 'corridor_pipeline_tracker.json')
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')
REPO = 'longfinnish/Corridor-Map'
TODAY = datetime.now()


def check_staleness():
    """Check all pipelines for stale data. Returns list of overdue items."""
    with open(TRACKER_FILE) as f:
        tracker = json.load(f)

    overdue = []

    for pipeline in tracker.get('gas_pipelines', []):
        name = pipeline.get('pipeline_name', 'Unknown')

        for data_type in ['ioc', 'unsub']:
            info = pipeline.get(data_type, {})
            status = info.get('status', '')
            freq = info.get('refresh_frequency_days')
            last = info.get('last_refreshed')
            method = info.get('access_method', '')
            url = info.get('url', '')

            # Skip pipelines that aren't captured or don't have a refresh schedule
            if status != 'captured' or freq is None or freq == 0:
                continue

            # If never refreshed, it's overdue
            if last is None:
                overdue.append({
                    'pipeline': name,
                    'data_type': data_type.upper(),
                    'method': method,
                    'url': url,
                    'freq_days': freq,
                    'last_refreshed': 'NEVER',
                    'days_overdue': 'N/A',
                })
                continue

            # Check if overdue
            try:
                last_date = datetime.strptime(last, '%Y-%m-%d')
                age_days = (TODAY - last_date).days
                max_age = freq * 1.5  # 50% grace period

                if age_days > max_age:
                    overdue.append({
                        'pipeline': name,
                        'data_type': data_type.upper(),
                        'method': method,
                        'url': url,
                        'freq_days': freq,
                        'last_refreshed': last,
                        'days_overdue': age_days - freq,
                    })
            except ValueError:
                pass

    return overdue


def create_github_issue(overdue_items):
    """Create a single GitHub Issue listing all overdue pipelines."""
    if not GITHUB_TOKEN:
        print("No GITHUB_TOKEN — skipping issue creation")
        return

    # Group by refresh method
    daily_auto = [i for i in overdue_items if i['method'] == 'daily_auto']
    monthly_manual = [i for i in overdue_items if i['method'] in ['quarterly_manual', 'browser_export']]
    other = [i for i in overdue_items if i not in daily_auto and i not in monthly_manual]

    body = f"## Gas Pipeline Data Staleness Report\n\n"
    body += f"**Generated:** {TODAY.strftime('%Y-%m-%d %H:%M')}\n"
    body += f"**Overdue items:** {len(overdue_items)}\n\n"

    if daily_auto:
        body += "### Daily Auto-Refresh Issues\n"
        body += "These should be refreshing automatically. If stale, check the GitHub Action logs.\n\n"
        for item in daily_auto:
            body += f"- **{item['pipeline']}** — {item['data_type']} | Last: {item['last_refreshed']} | {item['days_overdue']} days overdue\n"
        body += "\n"

    if monthly_manual:
        body += "### Monthly Manual Refresh Due\n"
        body += "Download from portal, upload to Claude for processing.\n\n"
        for item in monthly_manual:
            body += f"- **{item['pipeline']}** — {item['data_type']} | Last: {item['last_refreshed']} | Portal: {item['url'][:80] if item['url'] else 'See tracker'}\n"
        body += "\n"

    if other:
        body += "### Other\n"
        for item in other:
            body += f"- **{item['pipeline']}** — {item['data_type']} ({item['method']}) | Last: {item['last_refreshed']}\n"
        body += "\n"

    body += "---\n*Auto-generated by `scripts/check_gas_staleness.py`*\n"

    # Check for existing open staleness issue to avoid duplicates
    headers = {
        'Authorization': f'token {GITHUB_TOKEN}',
        'Accept': 'application/vnd.github.v3+json',
    }

    existing = requests.get(
        f'https://api.github.com/repos/{REPO}/issues',
        headers=headers,
        params={'labels': 'gas-staleness', 'state': 'open'},
        timeout=10,
    )

    if existing.status_code == 200 and existing.json():
        # Update existing issue instead of creating a new one
        issue_num = existing.json()[0]['number']
        r = requests.patch(
            f'https://api.github.com/repos/{REPO}/issues/{issue_num}',
            headers=headers,
            json={'body': body},
            timeout=10,
        )
        print(f"Updated existing issue #{issue_num}: {r.status_code}")
    else:
        # Create new issue
        r = requests.post(
            f'https://api.github.com/repos/{REPO}/issues',
            headers=headers,
            json={
                'title': f'Gas Data Staleness Alert — {len(overdue_items)} overdue ({TODAY.strftime("%Y-%m-%d")})',
                'body': body,
                'labels': ['gas-staleness'],
            },
            timeout=10,
        )
        print(f"Created issue: {r.status_code}")
        if r.status_code == 201:
            print(f"  URL: {r.json().get('html_url', '')}")


def main():
    print(f"Checking gas pipeline data staleness as of {TODAY.strftime('%Y-%m-%d')}...")

    if not os.path.exists(TRACKER_FILE):
        print(f"ERROR: Tracker file not found at {TRACKER_FILE}")
        sys.exit(1)

    overdue = check_staleness()

    if not overdue:
        print("All pipeline data is current. No issues to create.")
        return

    print(f"\n{len(overdue)} overdue items found:")
    for item in overdue:
        print(f"  {item['pipeline']:45s} {item['data_type']:5s} | Last: {item['last_refreshed']:12s} | Method: {item['method']}")

    create_github_issue(overdue)


if __name__ == '__main__':
    main()
